export const productsData = [
  {
    id: 1,
    quantity: 1,
    title: " بیالتی موکا اکسپرس ۱ فنجان",
    price: 6700000,
    type: "اسپرسو ساز",
    img: "/assets/images/mokaExpress.png",
  },
  {
    id: 2,
    quantity: 1,
    title: " آسیاب دستی بیالتی مدل Macinacaffee (مشکی رنگ)",
    price: 8050000,
    type: "اسپرسو ساز",
    img: "/assets/images/macinacaffee.png",
  },
  {
    id: 3,
    quantity: 1,
    title: " اسپرسوساز خانگی مباشی مدل ECM 2010 مشکی",
    price: 33000000,
    type: "اسپرسو ساز",
    img: "/assets/images/mebashi.png",
  },
  {
    id: 4,
    quantity: 1,
    title: " دستگاه اسپرسوساز دلونگی ECO311 (رنگ سفید)",
    price: 66000000,
    type: "اسپرسو ساز",
    img: "/assets/images/delongieco311.png",
  },
  {
    id: 5,
    quantity: 1,
    title: "شیکر استیل 700 میلی لیتر مدرج",
    price: 3600000,
    type: "اکسسوری",
    img: "/assets/images/delongieco311.png",
  },
  {
    id: 6,
    quantity: 1,
    title: " (۲۵۰ گرمی )قهوه ورونا",
    price: 1150000,
    type: "قهوه",
    img: "/assets/images/verona.png",
  },
  {
    id: 7,
    quantity: 1,
    title: " (۲۵۰ گرمی )قهوه آمورا",
    price: 1000000,
    type: "قهوه",
    img: "/assets/images/amora.png",
  },
  {
    id: 8,
    quantity: 1,
    title: " (۲۵۰ گرمی )قهوه ترکیبی تورینو",
    price: 1300000,
    type: "قهوه",
    img: "/assets/images/torino.png",
  },
  {
    id: 9,
    quantity: 1,
    title: " (۲۵۰ گرمی )قهوه باریستا",
    price: 1200000,
    type: "قهوه",
    img: "/assets/images/barista.png",
  },
  {
    id: 10,
    quantity: 1,
    title: " (۲۵۰ گرمی )قهوه صددرصد روبوستا Full Charge",
    price: 1350000,
    type: "قهوه",
    img: "/assets/images/fullcharge.png",
  },
  {
    id: 11,
    quantity: 1,
    title: " (۲۵۰ گرمی )قهوه برزیل ۵۰/۵۰",
    price: 1050000,
    type: "قهوه",
    img: "/assets/images/brazilcoffe.png",
  },
  {
    id: 12,
    quantity: 1,
    title: " (۲۵۰ گرمی )قهوه دان عربیکا رواندا",
    price: 1500000,
    type: "قهوه",
    img: "/assets/images/arabicarevanda.png",
  },
  {
    id: 13,
    quantity: 1,
    title: " (۲۵۰ گرمی )قهوه پرو 100% عربیکا",
    price: 1250000,
    type: "قهوه",
    img: "/assets/images/peru.png",
  },
  {
    id: 14,
    quantity: 1,
    title: "قهوه ساز دلونگی مدل bc0420",
    price: 56500000,
    type: "اسپرسو ساز",
    img: "/assets/images/delongibc420.png",
  },
  {
    id: 15,
    quantity: 1,
    title: "تمپر قهوه گتر مدل ارگونومی سایز 58",
    price: 2200000,
    type: "اکسسوری",
    img: "/assets/images/tamper.png",
  },
  {
    id: 16,
    quantity: 1,
    title: "پیچر شیر مخصوص لاته آرت و گرم کردن شیر تمام استیل ",
    price: 2900000,
    type: "اکسسوری",
    img: "/assets/images/picher.png",
  },
  {
    id: 17,
    quantity: 1,
    title: "زیر تمپری پلاستیکی ذوزنقه ای Gater (طوسی رنگ)",
    price: 1650000,
    type: "اکسسوری",
    img: "/assets/images/zirtampri.png",
  },
  {
    id: 18,
    quantity: 1,
    title: "ماگ استارباکس سبز ",
    price: 2200000,
    type: "اکسسوری",
    img: "/assets/images/magstarbox.png",
  },
];
